# Build settings

encoding: utf-8

#url: "http://localhost:4000"
url: "https://stpa.co" # the base hostname & protocol for your site

#markdown: redcarpet

highlighter: rouge

redcarpet:
  extensions: [ "with_toc_data", "xhtml", "autolink", "no_intra_emphasis", "fenced_code_blocks", "tables" ]

paginate: 5

gems:
  - jekyll-sitemap
  - jekyll-paginate

# Site settings
title: "Stewan Pacheco"
description: > # this means to ignore newlines until "email:"
  Fullstack Engineer and Js Evangelist

email: talk@stpa.co
#blog logos
logo: "https://graph.facebook.com/100002253653400/picture?width=115&height=115"
logo_footer: "/assets/images/stpa-symbol.png"

# blog cover
cover: "/assets/images/cover.gif"

name: 'Stewan P.'
author: 'Stewan Pacheco'
author_image: "https://graph.facebook.com/100002253653400/picture?width=115&height=115"
author_bio: >
 Fullstack Engineer and Js Evangelist.<br /> talk@stpa.co

excerpt_separator: "<!-- more -->"

comments: true

# readtime properties
# ---------------------
readtime: true
wpm:      200

baseurl: ""

# social icons and sharing options
social:
  - icon:  twitter
    url: https://twitter.com/stewones
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

 # - icon: facebook
  #  url:  https://facebook.com/stewones
  #  desc: Connect me at Facebook
  #  share_url: //www.facebook.com/sharer.php
  #  share_title: ?t=
  #  share_link: "&amp;u="

  - icon: github
    url:  https://github.com/stewones
    desc: Fork me on GitHub
    share_url: 
    share_title:
    share_link:

  - icon:  google-plus
    url: https://plus.google.com/118319296239885590925/posts
    desc:  Add me on Google+
    share_url:
    share_title:
    share_link:

# portfolio categories
projectsCategories:
  - name: Open Source
    slug: open-source

  - name: Jekyll
    slug: jekyll

  - name: AngularJS
    slug: angularjs

  - name: EmberJS
    slug: emberjs

  - name: PyroCMS
    slug: pyrocms

  - name: Bootstrap
    slug: bootstrap

# portfolio categories
projects:
  - name: Glamoux
    categories: ecommerce angularjs node mongodb
    link: https://www.glamoux.com
    image: https://glamoux-assets.s3.amazonaws.com/perfil-1024x1024.png
    desc: Costume jewelry e-commerce
    
  - name: Meditator
    categories: open-source jekyll
    link: https://meditator.stpa.co
    image: /assets/images/projects/thumb/thumb_meditator.jpg
    desc: Meditator is a medium inspired Jekyll blog theme

  - name: angular my modal
    categories: open-source bootstrap angularjs
    link: https://angular-my-modal.stpa.co
    image: /assets/images/projects/thumb/thumb_angular_modal.jpg
    desc: Provides a reusable way to do modals in angular

  - name: TickTask
    categories: bootstrap emberjs pyrocms
    link: https://tt.stpa.co
    image: /assets/images/projects/thumb/thumb_ticktask.jpg
    desc: An web app that will organize your financial life

  - name: Versão Comentada
    categories: bootstrap pyrocms
    link: http://www.versaocomentada.com.br
    image: /assets/images/projects/thumb/thumb_versao_comentada.jpg
    desc: Video blog with the most important fights commented

  - name: angular morris chart
    categories: open-source angularjs
    link: https://angular-morris-chart.stpa.co
    image: /assets/images/projects/thumb/thumb_angular_morris_chart.jpg
    desc: Provides wrapper directives of morris.js for angular 1.x
