# Build settings
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: [ "with_toc_data", "xhtml", "autolink" ]

gems:
  - jekyll-sitemap

# Site settings
title: "Stewan Pacheco"
description: > # this means to ignore newlines until "email:"
   Full stack developer, AngularJS & Laravel Lover. Currently works on an startup company, open-source believer in his spare time dedicates to contributing for community of development.

email: talk@stpa.co
#blog logos
logo: "https://graph.facebook.com/100002253653400/picture?width=115&height=115"
logo_footer: "/assets/images/stpa-symbol.png"

# blog cover
cover: "/assets/images/cover.gif"

name: 'Stewan P.'
author: 'Stewan Pacheco'
author_image: "https://graph.facebook.com/100002253653400/picture?width=115&height=115"
author_bio: >
   FullStack web developer, open source believer

paginate: 5

#url: "http://127.0.0.1:4000"
url: "https://stpa.co" # the base hostname & protocol for your site
excerpt_separator: "<!-- more -->"

comments: true

# readtime properties
# ---------------------
readtime: true
wpm:      200

baseurl: ""

# social icons and sharing options
social:
  - icon:  twitter
    url: https://twitter.com/stewones
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: facebook
    url:  https://facebook.com/stewones
    desc: Connect me at Facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/stewones
    desc: Fork me on GitHub
    share_url: 
    share_title:
    share_link:

  - icon:  google-plus
    url: https://plus.google.com/118319296239885590925/posts
    desc:  Add me on Google+
    share_url:
    share_title:
    share_link:
